env:
  global:
    - REPO="heartnotation"
    - TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

jobs:
  include:
    # Testing the API
    - stage: test
      name: Backend Tests
      language: go
      go:
        - "1.11.4"
      before_install:
        - export GOPATH="${TRAVIS_BUILD_DIR}/back"
        - mkdir -p ${TRAVIS_BUILD_DIR}/back/bin
        - export PATH="${TRAVIS_BUILD_DIR}/back/bin:$PATH"
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - cd back/src/restapi
      install:
        - dep ensure -vendor-only
      script:
        - find ./ -name '*_test.go' -printf '%h\n' | grep -v "vendor" | sort -u | xargs -n1 -P1 go test -v -cover

    # Deploying the API
    - stage: deploy
      name: Build and deploy the REST API to DockerHub
      if: branch = master AND tag IS blank
      language: go
      go: "1.11.4"
      services:
        - docker
      before_script:
        - export APP=$REPO/rest-api
      script:
        - docker build -t $APP:$TAG ./back
      deploy:
        provider: script
        script: bash .travis/deploy.sh

    # Testing the web application
    - stage: test
      name: Frontend Tests
      language: node_js
      node_js:
        - 11
      cache:
        directories:
          - node_modules
      before_install:
        - cd front
      install:
        - npm install
      script:
        - npm test

    # Deploying the web application
    - stage: deploy
      name: Build and deploy the web application to DockerHub
      if: branch = master AND tag IS blank
      language: node_js
      node_js:
        - 11
      services:
        - docker
      before_script:
        - export APP=$REPO/web-app
      script:
        - docker build -t $APP:$TAG ./front
      deploy:
        provider: script
        script: bash .travis/deploy.sh

    # Deploying the database
    - stage: deploy
      name: Deploying database to DockerHub
      if: branch = master AND tag IS blank
      language: go
      go: "1.11.4"
      services:
        - docker
      before_script:
        - export APP=$REPO/database
      script:
        - docker build -t $APP:$TAG ./db
      deploy:
        provider: script
        script: bash .travis/deploy.sh

    - stage: release
      name: Release source code to GitHub
      if: branch = master AND tag IS blank
      language: go
      go: "1.11.4"
      deploy:
        provider: releases
        api_key:
          secure: $TOKEN
        skip_cleanup: true
        name: "Heartnotation.$(date +'%d.%m.%Y %T')"
        overwrite: false

notifications:
  email: false
