version: "3"
services:
  server:
    build: ./back/
    env_file: ./.env
    ports:
      - 8000:8000
    depends_on:
      - database
  client:
    build:
      context: ./front/
      args:
        api: "${URL}"
        client_id: "${REACT_APP_CLIENT_ID}"
    env_file: ./.env
    ports:
      - 80:80
  database:
    build: ./db/
    ports:
      - 5432:5432
    volumes:
      - db-datas:/var/lib/postgresql/data
volumes:
  db-datas:
