version: '3'
services:
  server:
    build: ./back/
    ports:
      - 8000:8000
  client:
    build: ./front/
    ports:
      - 80:80
  database:
    build: ./db/
    ports:
      - 5432:5432
    volumes:
      - ./db/datas:/var/lib/postgresql/data

